version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
        ports:
            - 8000:8000
        command: python manage.py runserver
        env_file:
            - .env
    db:
        image: postgres:latest
        restart: always
        ports:
            - 5432
        volumes:
            - my_online_shop_db:/var/lib/postgresql/data/
        env_file:
            - .env
