# Generated by Django 3.2 on 2022-03-16 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import my_online_shop.shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_costs', models.FloatField(default=0.0)),
                ('freight', models.FloatField(default=5.0)),
                ('ready_to_checkout', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=16, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('account_type', models.CharField(choices=[('Normal', 'Normal'), ('Pro', 'Pro'), ('Premium', 'Premium')], default='Normal', max_length=16)),
                ('token', models.CharField(blank=True, max_length=256, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_picker', models.CharField(max_length=64)),
                ('phone_number_of_picker', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('In-store Pickup', 'In-store Pickup'), ('Home Delivery', 'Home Delivery')], max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('final_costs', models.FloatField()),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('arrived_date', models.DateTimeField(blank=True, null=True)),
                ('picked_up_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit_price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='product_specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'unique_together': {('product', 'group', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='product_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(max_length=1024, upload_to=my_online_shop.shop.models.product_picture.path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product_specification')),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('subtotal_costs', models.FloatField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
            options={
                'unique_together': {('inventory', 'order')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='inventories',
            field=models.ManyToManyField(through='shop.order_item', to='shop.inventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='color',
            field=models.ForeignKey(limit_choices_to={'group': 'color'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoty_of_this_color', to='shop.product_specification'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.ForeignKey(limit_choices_to={'group': 'size'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoty_of_this_size', to='shop.product_specification'),
        ),
        migrations.CreateModel(
            name='cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('subtotal_costs', models.FloatField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inventory')),
            ],
            options={
                'unique_together': {('inventory', 'cart')},
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='shop.cart_item', to='shop.inventory'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'color', 'size')},
        ),
        migrations.CreateModel(
            name='favorite_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
