# Generated by Django 3.2 on 2021-12-20 10:18

from django.db import migrations, models
import my_online_shop.shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_cart_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_picture",
            name="url",
        ),
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product_picture",
            name="picture",
            field=models.ImageField(
                default="what",
                max_length=1024,
                upload_to=my_online_shop.shop.models.product_picture.path,
            ),
            preserve_default=False,
        ),
    ]
