# Generated by Django 3.2 on 2021-12-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211220_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
