# Generated by Django 3.2 on 2022-02-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_favorite_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'unique_together': {('product', 'group', 'detail')},
            },
        ),
        migrations.AddField(
            model_name='product_picture',
            name='specification',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product_specification'),
            preserve_default=False,
        ),
    ]
