# Generated by Django 3.2 on 2022-02-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20220202_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='inventory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='shop.cart_item', to='shop.inventory'),
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('subtotal_costs', models.FloatField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.inventory')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='inventories',
            field=models.ManyToManyField(through='shop.order_item', to='shop.inventory'),
        ),
    ]
