# Generated by Django 3.2 on 2022-02-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220203_0531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='payment',
            new_name='order',
        ),
    ]
