# Generated by Django 3.2 on 2022-02-12 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220207_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ready_to_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='shop.customer'),
        ),
    ]
