# Generated by Django 3.2 on 2022-02-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20220212_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_card_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
