# Generated by Django 3.2.10 on 2021-12-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_name',
            field=models.CharField(default='anonymous', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Pro', 'Pro'), ('Premium', 'Premium')], default='Normal', max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='password', max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
