# Generated by Django 3.2.10 on 2021-12-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211218_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='shop.cart_item', to='shop.product'),
        ),
    ]
