# Generated by Django 3.2 on 2022-01-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
