# Generated by Django 3.2 on 2022-01-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_quantity_sold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="order_date",
            new_name="ordered_date",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="final_costs",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="done_date",
            new_name="paid_date",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="is_ordered",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="account_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(default="John Doe", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="address",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="arrived_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="picked_up_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="shipped_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                default="default@gmail.com", max_length=256, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Others", "Others")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="shop.cart"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="shop.customer"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[
                    ("Cash On Delivery", "Cash On Delivery"),
                    ("In-store Pickup", "In-store Pickup"),
                    ("Home Delivery", "Home Delivery"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shop.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together=set(),
        ),
    ]
