# Generated by Django 3.2 on 2022-02-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220202_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_sold',
        ),
        migrations.AlterField(
            model_name='product_specification',
            name='group',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=32),
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('inventory', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
