# Generated by Django 3.2 on 2022-02-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_cart_total_costs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart_item',
            unique_together={('inventory', 'cart')},
        ),
    ]
