# Generated by Django 3.2 on 2022-02-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_cart_item_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='freight',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart'),
        ),
    ]
