# Generated by Django 3.2 on 2022-02-06 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20220207_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_of_picker',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number_of_picker',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order'),
        ),
        migrations.AlterUniqueTogether(
            name='order_item',
            unique_together={('inventory', 'order')},
        ),
    ]
